
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Person__
#define __Person__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
    class Person;
}

class Person : public ::java::lang::Object
{

public:
  Person();
  Person(::java::lang::String *);
  ::java::lang::String * __attribute__((aligned(__alignof__( ::java::lang::Object)))) namewhatsoever;
  jint aviv;
  static ::java::lang::Class class$;
};

#endif // __Person__
