.PHONY = all, DFS, BFS

CC = clang++

DFS: ques1.cpp ques1_2.cpp
	$(CC) -std=gnu++11 -DDFS ques1.cpp -o ques1
	$(CC) -std=gnu++11 -DDFS ques1_2.cpp -o ques1_2
BFS: ques1.cpp ques1_2.cpp
	$(CC) -std=gnu++11 -DBFS ques1.cpp -o ques1
	$(CC) -std=gnu++11 ques1_2.cpp -o ques1_2
