#!/bin/bash 
cd /tmp/
touch 1 2 3 4 5 6 7 8 9 0 a b c d e f g h i j k l m n o p
strings=`ls -1tr | head -n -10`
for file in $strings; do 
	rmOutput=`rm -f -v $file`
	echo `date +%d-%m-%Y-%H-%M-%S`: $rmOutput
done

